# Generated by Django 3.2.6 on 2021-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogmodel_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
