# Generated by Django 3.2.6 on 2021-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
