# Generated by Django 3.2.6 on 2021-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
